# Tiny ImageNet-C sơ bộ trên Kaggle

Dùng Dataset hiện có: 200 lớp, JPEG 64×64, tên `test_*.JPEG`. **1 panel, 3 kịch bản, W=0/4/16, source/norm/Tent/SAR, reset none/all: 72 cặp, 144 lượt Q.** Prefix=512, washout tối đa=512, Q=512, batch size=32.

Mô hình: ResNet50 ImageNet-1K V1 pretrained, chỉ giữ 200 logits tương ứng các synset của Dataset **trước** khi tính softmax, entropy và loss. Dùng transform của trọng số ImageNet (resize 256, crop 224). Không huấn luyện mô hình nguồn Tiny; kết quả là exploratory transfer trên Tiny, không phải kết quả Stage B ImageNet-C hay baseline Tiny đã được huấn luyện.

**Trước Run All:** bật GPU + Internet; Add Input Dataset nguồn mới từ `streaming-tta-kaggle-tiny-source.zip`; giữ Dataset ảnh hiện có. Có thể giữ Input nguồn cũ: notebook chỉ chọn nguồn chứa `scripts/tiny_imagenetc.py`. Xem `research/kaggle_tiny_preliminary.md`.

In [1]:
import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
from pathlib import Path
import shutil, subprocess, sys, json, zipfile, tempfile

INPUT = Path("/kaggle/input")
WORK = Path("/kaggle/working")
REPO = WORK / "streaming-tta-tiny-state-memory"
sources = [
    p.parent.parent for p in INPUT.rglob("tiny_imagenetc.py")
    if p.parent.name == "scripts"
    and (p.parent.parent / "src/historytta").is_dir()
    and (p.parent.parent / "configs/kaggle_tiny_preliminary.yaml").is_file()
]
if not REPO.exists():
    if len(sources) == 1:
        shutil.copytree(sources[0], REPO)
    elif not sources:
        bundles = list(INPUT.rglob("streaming-tta-kaggle-tiny-source.zip"))
        if len(bundles) != 1:
            raise RuntimeError("Add Input the NEW source bundle streaming-tta-kaggle-tiny-source.zip.")
        with tempfile.TemporaryDirectory(prefix="tiny_source_", dir=WORK) as temp:
            temp = Path(temp)
            with zipfile.ZipFile(bundles[0]) as archive:
                if sum(i.file_size for i in archive.infolist()) > 100_000_000:
                    raise RuntimeError("Unexpectedly large source bundle.")
                expected_root = temp / "streaming-tta-state-memory"
                for info in archive.infolist():
                    if not (temp / info.filename).resolve().is_relative_to(expected_root.resolve()):
                        raise RuntimeError("Unexpected ZIP path: " + info.filename)
                    if (info.external_attr >> 16) & 0o170000 == 0o120000:
                        raise RuntimeError("Source symlinks are not supported.")
                archive.extractall(temp)
            shutil.copytree(expected_root, REPO)
    else:
        raise RuntimeError("Multiple NEW source Datasets found; keep exactly one.")
if not (REPO / "scripts/tiny_imagenetc.py").is_file():
    raise RuntimeError("Tiny source is missing. Attach the new bundle and use a fresh session.")
os.chdir(REPO)
print("Tiny repository:", REPO)

Tiny repository: /kaggle/working/streaming-tta-tiny-state-memory

## 1. Tự tìm dữ liệu

Nguồn mặc định là Dataset bạn đang dùng. Nếu đổi Dataset, sửa `DATA_SOURCE_URL`. Không sửa batch size, W hay các counts để bỏ qua lỗi. Sampler giữ hash split pilot/reserve, không lấy ảnh reserve khi thiếu pilot.

In [2]:
DATA_SOURCE_URL = "https://www.kaggle.com/datasets/husnifdu/imagenet-c"
domains = ["gaussian_noise", "brightness", "defocus_blur"]
roots = [
    p.parent for p in INPUT.rglob("gaussian_noise")
    if all((p.parent / d / "5").is_dir() for d in domains)
]
if len(roots) != 1:
    print("Candidate image roots:", roots)
    raise RuntimeError("Attach one Tiny ImageNet-C Dataset containing all three corruption/5 directories.")
DATA_ROOT = roots[0]
CONFIG = REPO / "configs/kaggle_tiny_preliminary.yaml"
CLASS_INDEX = REPO / "datasets/metadata/imagenet_class_index.json"
DOWNLOAD_CLASS_INDEX = True
MAX_HOURS = 10.0
EXPORT_DIR = WORK / "kaggle_tiny_exports"

print("DATA_ROOT:", DATA_ROOT)
for domain in domains:
    variant = DATA_ROOT / domain / "5"
    count = sum(p.is_dir() for p in variant.iterdir())
    print(domain, "classes:", count)
    if count != 200:
        raise RuntimeError("This notebook requires exactly 200 Tiny classes in every variant.")

DATA_ROOT: /kaggle/input/datasets/husnifdu/imagenet-c/ImageNet-C
gaussian_noise classes: 200
brightness classes: 200
defocus_blur classes: 200

## 2. Kiểm tra môi trường

Giữ Torch/torchvision sẵn có của Kaggle. Internet dùng để lấy mapping ImageNet 35 KB, trọng số ResNet50 V1 và gói nhỏ còn thiếu. Notebook không tải archive ảnh.

In [3]:
import importlib.util
for module in ["torch", "torchvision"]:
    if importlib.util.find_spec(module) is None:
        raise RuntimeError("Use a Kaggle GPU image with " + module)
packages = {"yaml": "PyYAML", "numpy": "numpy", "pandas": "pandas", "scipy": "scipy",
            "matplotlib": "matplotlib", "PIL": "Pillow", "pytest": "pytest", "nbformat": "nbformat"}
missing = [package for module, package in packages.items() if importlib.util.find_spec(module) is None]
if missing:
    subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)
import torch, torchvision
if not torch.cuda.is_available():
    raise RuntimeError("Enable GPU in Kaggle Settings.")
print("Torch:", torch.__version__, "torchvision:", torchvision.__version__)
print("CUDA:", torch.version.cuda, "GPU:", torch.cuda.get_device_name(0))
probe = torch.ones((8, 8), device="cuda")
print("CUDA smoke:", (probe @ probe).mean().item())
del probe
torch.cuda.empty_cache()

Torch: 2.10.0+cu128 torchvision: 0.25.0+cu128
CUDA: 12.8 GPU: Tesla T4
CUDA smoke: 8.0

## 3. Kế hoạch và tests nhỏ

Tests dùng fixtures CPU, không tải trọng số ResNet50. Đây là kiểm tra code, không phải kết quả Tiny thật.

In [4]:
def helper(*arguments):
    subprocess.run([sys.executable, "-u", "scripts/kaggle_preliminary.py",
                    *map(str, arguments), "--config", str(CONFIG)], cwd=REPO, check=True)

helper("plan")
subprocess.run([sys.executable, "-m", "pytest", "-q",
                "tests/test_tiny_imagenetc.py", "tests/test_adapters.py",
                "tests/test_protocol.py", "tests/test_evaluate.py"], cwd=REPO, check=True)

{
  "mode": "plan_only",
  "config": {
    "experiment_id": "tiny_imagenetc_kaggle_preliminary_v1",
    "stage": "TINY",
    "dataset": "Tiny ImageNet-C",
    "dataset_profile": "tiny_imagenet_c",
    "output": "results/tiny_imagenetc_kaggle_preliminary_v1",
    "manifest_index": "datasets/processed/tiny-imagenet-c-kaggle-preliminary/index.json",
    "class_index": "datasets/metadata/imagenet_class_index.json",
    "backbone": "resnet50",
    "weights": "IMAGENET1K_V1",
    "classifier": "imagenet_200_class_projection",
    "expected_classes": 200,
    "device": "cuda",
    "threads": 2,
    "methods": [
      "source",
      "norm",
      "tent",
      "sar_complete"
    ],
    "washout_batches": [
      0,
      4,
      16
    ],
    "interventions": [
      "none",
      "all"
    ],
    "adaptation": {
      "batch_size": 32,
      "lr": 0.00025,
      "momentum": 0.9,
      "reset_threshold": 0.2,
      "sar_margin": 2.1193269466192146
    },
    "save_junctions": false,
    "interpretation": "Exploratory Tiny ImageNet-C, one panel; ImageNet-pretrained ResNet50 projected to 200 dataset synsets, input resized to 224. Not a Tiny-trained baseline or Stage B ImageNet-C result.",
    "planning": {
      "independent_panels": 1,
      "scenarios_per_panel": 3,
      "prefix_images": 512,
      "washout_images_max": 512,
      "suffix_images": 512,
      "gpu_hours_low": 0,
      "gpu_hours_high": 10,
      "disk_gb": 5,
      "observed_gpu_usd_per_hour": 0,
      "requested_total_budget_usd": 0,
      "provider": "kaggle",
      "paid_approval_status": "not_applicable_free_quota"
    }
  },
  "matrix": {
    "independent_image_panels": 1,
    "reused_scenarios_per_panel": 3,
    "unique_base_images": 1536,
    "paired_suffix_runs": 72,
    "directional_suffix_runs": 144,
    "main_suffix_image_forwards": 73728,
    "saved_junction_checkpoints": 0,
    "model_state_copies_in_junctions": 0,
    "junction_storage_note": "Each junction stores both current model state and the immutable source anchor, plus optimizer/auxiliary/RNG state. Budget approximately twice model-state bytes per junction, with additional serialization/state overhead.",
    "note": "Counts exclude histories, shared tails, parity/replay controls and SAR second forwards/backward computation."
  },
  "budget": {
    "gpu_hours": [
      0,
      10
    ],
    "gpu_cost_usd": [
      0,
      0
    ],
    "disk_gb": 5,
    "requested_ceiling_usd": 0
  },
  "interpretation": "Exploratory Tiny ImageNet-C, one panel; ImageNet-pretrained ResNet50 projected to 200 dataset synsets, input resized to 224. Not a Tiny-trained baseline or Stage B ImageNet-C result.",
  "scheduling_note": "0-10h is an allowance, not a benchmark; Kaggle quota must be checked in your account."
}
.............................................                            [100%]
=============================== warnings summary ===============================
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64
  /usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
    prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))

../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85
  /usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
    parse = parser.parseString(pattern)

../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89
../../../usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89
  /usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
    parser.resetCache()

../../../usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45
  /usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
    ParserElement.enablePackrat()

tests/test_adapters.py::test_tent_matches_pinned_reference_over_momentum_steps
tests/test_adapters.py::test_sar_matches_pinned_reference_nonempty_no_recovery
  /usr/local/lib/python3.12/dist-packages/torch/jit/_script.py:1480: DeprecationWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
45 passed, 16 warnings in 22.11s

CompletedProcess(args=['/usr/bin/python3', '-m', 'pytest', '-q', 'tests/test_tiny_imagenetc.py', 'tests/test_adapters.py', 'tests/test_protocol.py', 'tests/test_evaluate.py'], returncode=0)

## 4. Tạo manifest Tiny

Mapping nhãn 0..199 được tạo theo thứ tự synset và ánh xạ sang chỉ số ImageNet gốc. Ba corruption phải cùng ID và lớp. JPEG được chọn phải 64×64. Cần **1536 ID pilot**, tương ứng 4608 file JPEG qua ba corruption. Mirror được ghi rõ nguồn khai báo và hash ảnh được chọn; không tuyên bố đã kiểm MD5 archive chính thức.

In [5]:
arguments = ["prepare", "--data-root", DATA_ROOT, "--source-url", DATA_SOURCE_URL,
             "--class-index", CLASS_INDEX]
if DOWNLOAD_CLASS_INDEX:
    arguments.append("--download-class-index")
helper(*arguments)

{
  "index": "/kaggle/working/streaming-tta-tiny-state-memory/datasets/processed/tiny-imagenet-c-kaggle-preliminary/index.json",
  "dataset": "Tiny ImageNet-C",
  "classes": 200,
  "panels": 3,
  "unique_base_images": 1536,
  "available_pilot_ids": 2060,
  "classifier": "imagenet_200_class_projection",
  "provenance_mode": "declared_attached_dataset"
}

## 5. Chạy, audit và xuất ZIP

Mọi adaptation loss được tính trên 200 logits. SAR margin=0.4×log(200). Runner chỉ dùng GPU đầu tiên. Cap subprocess 10 giờ không bao gồm chuẩn bị dữ liệu, tests hoặc render hình.

Kết quả hoàn chỉnh cần run_status=complete, audit passed và tất cả controls đạt. `finally` xuất diagnostics cả khi runner lỗi; nếu Kaggle dừng cả session thì xuất ZIP không được bảo đảm. Không tự sửa trạng thái thành complete. Để chạy lại, đổi cả experiment_id/output; để export lại chọn thư mục EXPORT_DIR mới.

In [6]:
try:
    helper("run", "--max-hours", MAX_HOURS)
finally:
    helper("export", "--export-dir", EXPORT_DIR)

print("Download from Kaggle Output:", EXPORT_DIR)

Running: scripts/tiny_imagenetc.py --config /kaggle/working/streaming-tta-tiny-state-memory/configs/kaggle_tiny_preliminary.yaml --execute --max-hours 10.0
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth

  0%|          | 0.00/97.8M [00:00<?, ?B/s]
  5%|▌         | 5.12M/97.8M [00:00<00:01, 52.3MB/s]
 10%|█         | 10.1M/97.8M [00:00<00:01, 50.0MB/s]
 28%|██▊       | 27.6M/97.8M [00:00<00:00, 109MB/s]
 46%|████▌     | 45.0M/97.8M [00:00<00:00, 137MB/s]
 64%|██████▍   | 62.6M/97.8M [00:00<00:00, 154MB/s]
 82%|████████▏ | 80.4M/97.8M [00:00<00:00, 165MB/s]
100%|██████████| 97.8M/97.8M [00:00<00:00, 144MB/s]
tiny_pilot_seed101 gaussian_noise+brightness__to__defocus_blur source completed
tiny_pilot_seed101 gaussian_noise+brightness__to__defocus_blur norm completed
tiny_pilot_seed101 gaussian_noise+brightness__to__defocus_blur tent completed
tiny_pilot_seed101 gaussian_noise+brightness__to__defocus_blur sar_complete completed
tiny_pilot_seed101 defocus_blur+gaussian_noise__to__brightness source completed
tiny_pilot_seed101 defocus_blur+gaussian_noise__to__brightness norm completed
tiny_pilot_seed101 defocus_blur+gaussian_noise__to__brightness tent completed
tiny_pilot_seed101 defocus_blur+gaussian_noise__to__brightness sar_complete completed
tiny_pilot_seed101 brightness+defocus_blur__to__gaussian_noise source completed
tiny_pilot_seed101 brightness+defocus_blur__to__gaussian_noise norm completed
tiny_pilot_seed101 brightness+defocus_blur__to__gaussian_noise tent completed
tiny_pilot_seed101 brightness+defocus_blur__to__gaussian_noise sar_complete completed
Running: scripts/evaluate.py --results results/tiny_imagenetc_kaggle_preliminary_v1
{
  "passed": true,
  "counts": {
    "run_rows": 144,
    "paired_rows": 72,
    "predictions_audited": 144,
    "pairs_audited": 72,
    "scalar_comparisons": 1368,
    "manifest_checks": 144,
    "unique_original_ids": 512,
    "panel_scenario_groups": 3
  },
  "failure_count": 0,
  "output": "results/tiny_imagenetc_kaggle_preliminary_v1/evaluation_audit.json"
}
Running: scripts/generate_tables.py --results results/tiny_imagenetc_kaggle_preliminary_v1 --stage TINY
{
  "results": "/kaggle/working/streaming-tta-tiny-state-memory/results/tiny_imagenetc_kaggle_preliminary_v1",
  "stage": "TINY",
  "caption": "Stage TINY: recorded experiment results. Scenarios are averaged within each seed/panel, then repeated seeds within panel_id; each panel receives equal weight. SD and 95% t intervals describe variation across the supplied panel IDs, conditional on this dataset, model, and stream construction. Tiny local samples and three seeds cannot establish population generalization. Shared-image scenarios, suffix batches, and repeated seeds are not counted as independent panels. No p-values or statistical-superiority claims are generated. Metrics remain in raw units: accuracy/error fractions, NLL in nats/example; absolute gaps are finite-panel magnitudes, not unbiased absolute population effects.",
  "aggregation": "mean scenarios -> mean repeated seeds -> equal panel summary",
  "pvalues_computed": false,
  "partial_import": false,
  "generated": [
    "source_reference_matched_rows.csv",
    "norm_reference_matched_rows.csv",
    "performance_reset_effects_matched_rows.csv",
    "paired_seed_panels.csv",
    "paired_panels.csv",
    "paired_summary.csv",
    "paired_seed_descriptive.csv",
    "runs_seed_panels.csv",
    "runs_panels.csv",
    "runs_summary.csv",
    "runs_seed_descriptive.csv",
    "reset_effects_seed_panels.csv",
    "reset_effects_panels.csv",
    "reset_effects_summary.csv",
    "reset_effects_seed_descriptive.csv",
    "source_reference_seed_panels.csv",
    "source_reference_panels.csv",
    "source_reference_summary.csv",
    "source_reference_seed_descriptive.csv",
    "norm_reference_seed_panels.csv",
    "norm_reference_panels.csv",
    "norm_reference_summary.csv",
    "norm_reference_seed_descriptive.csv",
    "performance_reset_effects_seed_panels.csv",
    "performance_reset_effects_panels.csv",
    "performance_reset_effects_summary.csv",
    "performance_reset_effects_seed_descriptive.csv",
    "controls.csv",
    "tables.md"
  ],
  "analysis_script_sha256": {
    "generate_tables.py": "42c41ba460a2cd0ec830be7e6809a39008b6302528b6e91b3aeb5bb04288e602",
    "generate_figures.py": "bbecb74e71e9a53b9ec379f26937b3336290ba6432e7003e4fbe25b51520070c",
    "evaluate.py": "9f78893ede5ffd10a8b77178054185e9e192e6a5714c2b115d32bd399f689e7d"
  },
  "input_sha256": {
    "paired.csv": "75b13765363e1e4de073f8dc9150b53932c63ca6eaeb0ba7b432bc0f47cf5997",
    "runs.csv": "fd7e1d68f65837da06735d8e0fc04936b368447474e9d165be052a72e7b96609",
    "controls.json": "b1f112cc8e958ba4a6cca598f57e9c5a1c52ac1316b84ad70fd3b59c5b20bb76",
    "run_status.json": "3935192f11ebb4ccdc88ec3ee5c70f95d807428cc739633631f979c86cb6f6af"
  }
}
Running: scripts/generate_figures.py --results results/tiny_imagenetc_kaggle_preliminary_v1 --output results/tiny_imagenetc_kaggle_preliminary_v1/figures --stage TINY
{
  "results": "/kaggle/working/streaming-tta-tiny-state-memory/results/tiny_imagenetc_kaggle_preliminary_v1",
  "stage": "TINY",
  "scope": "Stage TINY: recorded experiment results. Scenarios are averaged within each seed/panel, then repeated seeds within panel_id; each panel receives equal weight. SD and 95% t intervals describe variation across the supplied panel IDs, conditional on this dataset, model, and stream construction. Tiny local samples and three seeds cannot establish population generalization. Shared-image scenarios, suffix batches, and repeated seeds are not counted as independent panels. No p-values or statistical-superiority claims are generated. Metrics remain in raw units: accuracy/error fractions, NLL in nats/example; absolute gaps are finite-panel magnitudes, not unbiased absolute population effects.",
  "figures": [
    {
      "name": "disagreement_washout",
      "caption": "No external reset. Thin lines are individual panel means after averaging reused scenarios and seeds; diamonds average panels equally. Disagreement indicates different decisions, not necessarily worse accuracy. No interpolation-based recovery-time claim or statistical-significance claim is made.",
      "files": [
        "disagreement_washout.png",
        "disagreement_washout.pdf",
        "disagreement_washout.svg"
      ]
    },
    {
      "name": "state_reset_effects",
      "caption": "Each contrast pairs the exact scenario/seed/panel/W with its no-reset reference before aggregation. Circles show panels and diamonds their mean. Negative values reduce history disagreement; they do not establish improved accuracy or identify a unique cause. Auxiliary-state resets include exactly the components declared by the runner; unknown intervention identifiers are printed verbatim.",
      "files": [
        "state_reset_effects.png",
        "state_reset_effects.pdf",
        "state_reset_effects.svg"
      ]
    },
    {
      "name": "protocol_schematic",
      "caption": "Experimental protocol schematic, not measured data. Prefixes differ only in immutable-batch block order; H/W/Q are disjoint by original identity. Common-tail length and intervention are recorded conditions. The intervention occurs after W and before pre-update Q prediction.",
      "files": [
        "protocol_schematic.png",
        "protocol_schematic.pdf",
        "protocol_schematic.svg"
      ]
    }
  ],
  "skipped": [
    "factorial contrasts: no complete eight-cell P/O/aux trajectory",
    "training curves: recorded epoch data unavailable",
    "qualitative outcomes: no matched pair with recorded images"
  ],
  "partial_import": false,
  "analysis_script_sha256": {
    "generate_tables.py": "42c41ba460a2cd0ec830be7e6809a39008b6302528b6e91b3aeb5bb04288e602",
    "generate_figures.py": "bbecb74e71e9a53b9ec379f26937b3336290ba6432e7003e4fbe25b51520070c",
    "evaluate.py": "9f78893ede5ffd10a8b77178054185e9e192e6a5714c2b115d32bd399f689e7d"
  },
  "input_sha256": {
    "paired.csv": "75b13765363e1e4de073f8dc9150b53932c63ca6eaeb0ba7b432bc0f47cf5997",
    "runs.csv": "fd7e1d68f65837da06735d8e0fc04936b368447474e9d165be052a72e7b96609",
    "controls.json": "b1f112cc8e958ba4a6cca598f57e9c5a1c52ac1316b84ad70fd3b59c5b20bb76",
    "run_status.json": "3935192f11ebb4ccdc88ec3ee5c70f95d807428cc739633631f979c86cb6f6af"
  }
}

W16 results, disagreement in percentage points:
                                   scenario       method intervention  disagreement_pp   nll_gap
gaussian_noise+brightness__to__defocus_blur       source         none         0.000000  0.000000
gaussian_noise+brightness__to__defocus_blur       source          all         0.000000  0.000000
gaussian_noise+brightness__to__defocus_blur         norm         none         0.000000  0.000000
gaussian_noise+brightness__to__defocus_blur         norm          all         0.000000  0.000000
gaussian_noise+brightness__to__defocus_blur         tent         none         8.593750  0.002793
gaussian_noise+brightness__to__defocus_blur         tent          all         0.000000  0.000000
gaussian_noise+brightness__to__defocus_blur sar_complete         none         0.000000  0.000000
gaussian_noise+brightness__to__defocus_blur sar_complete          all         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness       source         none         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness       source          all         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness         norm         none         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness         norm          all         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness         tent         none         4.296875 -0.000219
defocus_blur+gaussian_noise__to__brightness         tent          all         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness sar_complete         none         0.000000  0.000000
defocus_blur+gaussian_noise__to__brightness sar_complete          all         0.000000  0.000000
brightness+defocus_blur__to__gaussian_noise       source         none         0.000000  0.000000
brightness+defocus_blur__to__gaussian_noise       source          all         0.000000  0.000000
brightness+defocus_blur__to__gaussian_noise         norm         none         0.000000  0.000000
brightness+defocus_blur__to__gaussian_noise         norm          all         0.000000  0.000000
brightness+defocus_blur__to__gaussian_noise         tent         none         6.445312  0.003976
brightness+defocus_blur__to__gaussian_noise         tent          all         0.000000  0.000000
brightness+defocus_blur__to__gaussian_noise sar_complete         none        23.632812  0.005045
brightness+defocus_blur__to__gaussian_noise sar_complete          all         0.000000  0.000000
{
  "archive": "/kaggle/working/kaggle_tiny_exports/tiny_imagenetc_kaggle_preliminary_v1_artifacts.zip",
  "sha256": "c92feebbe1a2db0fa97258be44ebf85c53cb985a5bd2e12551dfaa6385518653",
  "note": "May contain partial/failed results; check run_status and audit before interpretation."
}
Download from Kaggle Output: /kaggle/working/kaggle_tiny_exports

## 6. Đọc W16 và accuracy

Q=512: một quyết định khác tương ứng 0.1953125 điểm phần trăm. Giữ từng kịch bản riêng khi xem bảng. Disagreement không tự biểu thị lợi/hại, và bằng 0 không đảm bảo logits/loss giống nhau.

Hai CSV chính nằm trong results: `preliminary_history.csv`, `preliminary_performance.csv`. ZIP gồm source anchor, mapping/projected indices, NPZ, manifests, logs, bảng/hình; không gồm ảnh Input. Kết quả chỉ thuộc **Tiny exploratory transfer**, không so trực tiếp với số Stage A/Stage B ImageNet-C.

In [7]:
import pandas as pd
import yaml
from IPython.display import display, FileLink

cfg = yaml.safe_load(CONFIG.read_text())
RESULTS = REPO / cfg["output"]
status = json.loads((RESULTS / "run_status.json").read_text())
audit = json.loads((RESULTS / "evaluation_audit.json").read_text())
controls = json.loads((RESULTS / "controls.json").read_text())
assert status["status"] == "complete" and audit["passed"]
assert controls and all(c["passed"] for c in controls)
print("Run:", status)
print("Audit:", audit["counts"])
history = pd.read_csv(RESULTS / "preliminary_history.csv")
display(history[history.washout_batches == 16])
performance = pd.read_csv(RESULTS / "preliminary_performance.csv")
display(performance[(performance.washout_batches == 16) & (performance.intervention == "none")])
archive = EXPORT_DIR / (cfg["experiment_id"] + "_artifacts.zip")
print("ZIP:", archive)
display(FileLink(str(archive)))

Run: {'status': 'complete', 'stage': 'TINY', 'seconds': 1608.3985719490001, 'controls_passed': 210, 'controls_total': 210, 'interpretation': 'Exploratory Tiny ImageNet-C, one panel; ImageNet-pretrained ResNet50 projected to 200 dataset synsets, input resized to 224. Not a Tiny-trained baseline or Stage B ImageNet-C result.'}
Audit: {'run_rows': 144, 'paired_rows': 72, 'predictions_audited': 144, 'pairs_audited': 72, 'scalar_comparisons': 1368, 'manifest_checks': 144, 'unique_original_ids': 512, 'panel_scenario_groups': 3}

,panel_id,scenario,method,washout_batches,intervention,n,disagreement,absolute_error_gap,nll_gap,first_batch_max_logit_diff,disagreement_pp
4,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,source,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
5,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,source,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
10,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,norm,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
11,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,norm,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
16,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,tent,16,none,512,0.085938,0.005859,0.002793,0.317001,8.593750
17,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,tent,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
22,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,sar_complete,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
23,tiny_pilot_seed101,gaussian_noise+brightness__to__defocus_blur,sar_complete,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
28,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,source,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
29,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,source,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
34,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,norm,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
35,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,norm,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
40,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,tent,16,none,512,0.042969,0.001953,-0.000219,0.432941,4.296875
41,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,tent,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
46,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,sar_complete,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
47,tiny_pilot_seed101,defocus_blur+gaussian_noise__to__brightness,sar_complete,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
52,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,source,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
53,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,source,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
58,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,norm,16,none,512,0.000000,0.000000,0.000000,0.000000,0.000000
59,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,norm,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
64,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,tent,16,none,512,0.064453,0.000000,0.003976,0.272372,6.445312
65,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,tent,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000
70,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,sar_complete,16,none,512,0.236328,0.007812,0.005045,1.316115,23.632812
71,tiny_pilot_seed101,brightness+defocus_blur__to__gaussian_noise,sar_complete,16,all,512,0.000000,0.000000,0.000000,0.000000,0.000000

,scenario,method,washout_batches,intervention,accuracy,nll,brier,ece15,accuracy_percent
5,brightness+defocus_blur__to__gaussian_noise,norm,16,none,0.060547,5.029103,1.002339,0.090400,6.054688
11,brightness+defocus_blur__to__gaussian_noise,sar_complete,16,none,0.060547,5.022064,1.004588,0.093735,6.054688
17,brightness+defocus_blur__to__gaussian_noise,source,16,none,0.070312,5.541301,1.085905,0.262069,7.031250
23,brightness+defocus_blur__to__gaussian_noise,tent,16,none,0.066406,4.954335,1.003536,0.102278,6.640625
29,defocus_blur+gaussian_noise__to__brightness,norm,16,none,0.273438,3.298399,0.849415,0.057761,27.343750
35,defocus_blur+gaussian_noise__to__brightness,sar_complete,16,none,0.298828,3.122173,0.821354,0.067478,29.882812
41,defocus_blur+gaussian_noise__to__brightness,source,16,none,0.277344,3.577870,0.899980,0.171033,27.734375
47,defocus_blur+gaussian_noise__to__brightness,tent,16,none,0.303711,3.120101,0.823764,0.069602,30.371094
53,gaussian_noise+brightness__to__defocus_blur,norm,16,none,0.111328,4.636339,0.980201,0.101673,11.132812
59,gaussian_noise+brightness__to__defocus_blur,sar_complete,16,none,0.111328,4.607400,0.976098,0.102916,11.132812
65,gaussian_noise+brightness__to__defocus_blur,source,16,none,0.123047,5.029201,1.029378,0.238674,12.304688
71,gaussian_noise+brightness__to__defocus_blur,tent,16,none,0.133789,4.533045,0.979911,0.101158,13.378906

ZIP: /kaggle/working/kaggle_tiny_exports/tiny_imagenetc_kaggle_preliminary_v1_artifacts.zip

/kaggle/working/kaggle_tiny_exports/tiny_imagenetc_kaggle_preliminary_v1_artifacts.zip